language: java
jdk:
  - openjdk8
  - openjdk9
  - openjdk11
  - oraclejdk9
  - oraclejdk11
before_install:
  - sudo apt-get install -q libgfortran3
after_success:
  - bash <(curl -s https://codecov.io/bash)
